[package]
name = "kind2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
TSPL = "0.0.1"
im = "15.1.0"
